# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\movie_app\src\ui\movie_app.ui'
#
# Created: Sun Dec 17 18:45:54 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Movie_app(object):
    def setupUi(self, Movie_app):
        Movie_app.setObjectName("Movie_app")
        Movie_app.resize(1383, 910)
        Movie_app.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtGui.QWidget(Movie_app)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_drives = QtGui.QHBoxLayout()
        self.layout_drives.setObjectName("layout_drives")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.layout_drives.addWidget(self.label)
        self.line_drive_a = QtGui.QLineEdit(self.centralwidget)
        self.line_drive_a.setObjectName("line_drive_a")
        self.layout_drives.addWidget(self.line_drive_a)
        self.button_browse_a = QtGui.QPushButton(self.centralwidget)
        self.button_browse_a.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_browse_a.setObjectName("button_browse_a")
        self.layout_drives.addWidget(self.button_browse_a)
        spacerItem = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layout_drives.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.layout_drives.addWidget(self.label_2)
        self.line_drive_b = QtGui.QLineEdit(self.centralwidget)
        self.line_drive_b.setObjectName("line_drive_b")
        self.layout_drives.addWidget(self.line_drive_b)
        self.button_browse_b = QtGui.QPushButton(self.centralwidget)
        self.button_browse_b.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_browse_b.setObjectName("button_browse_b")
        self.layout_drives.addWidget(self.button_browse_b)
        spacerItem1 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layout_drives.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_drives)
        self.layout_inboxes = QtGui.QHBoxLayout()
        self.layout_inboxes.setObjectName("layout_inboxes")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.layout_inboxes.addWidget(self.label_4)
        self.line_inbox_a = QtGui.QLineEdit(self.centralwidget)
        self.line_inbox_a.setObjectName("line_inbox_a")
        self.layout_inboxes.addWidget(self.line_inbox_a)
        self.button_browse_a_inbox = QtGui.QPushButton(self.centralwidget)
        self.button_browse_a_inbox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_browse_a_inbox.setObjectName("button_browse_a_inbox")
        self.layout_inboxes.addWidget(self.button_browse_a_inbox)
        spacerItem2 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layout_inboxes.addItem(spacerItem2)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.layout_inboxes.addWidget(self.label_3)
        self.line_inbox_b = QtGui.QLineEdit(self.centralwidget)
        self.line_inbox_b.setObjectName("line_inbox_b")
        self.layout_inboxes.addWidget(self.line_inbox_b)
        self.button_browse_b_inbox = QtGui.QPushButton(self.centralwidget)
        self.button_browse_b_inbox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.button_browse_b_inbox.setObjectName("button_browse_b_inbox")
        self.layout_inboxes.addWidget(self.button_browse_b_inbox)
        spacerItem3 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layout_inboxes.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.layout_inboxes)
        self.laout_vloume_names = QtGui.QHBoxLayout()
        self.laout_vloume_names.setObjectName("laout_vloume_names")
        self.label_volume_a = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_volume_a.sizePolicy().hasHeightForWidth())
        self.label_volume_a.setSizePolicy(sizePolicy)
        self.label_volume_a.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_volume_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume_a.setObjectName("label_volume_a")
        self.laout_vloume_names.addWidget(self.label_volume_a)
        self.label_volume_b = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_volume_b.sizePolicy().hasHeightForWidth())
        self.label_volume_b.setSizePolicy(sizePolicy)
        self.label_volume_b.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_volume_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume_b.setObjectName("label_volume_b")
        self.laout_vloume_names.addWidget(self.label_volume_b)
        self.verticalLayout.addLayout(self.laout_vloume_names)
        self.button_list_all = QtGui.QPushButton(self.centralwidget)
        self.button_list_all.setObjectName("button_list_all")
        self.verticalLayout.addWidget(self.button_list_all)
        self.button_list_unique = QtGui.QPushButton(self.centralwidget)
        self.button_list_unique.setObjectName("button_list_unique")
        self.verticalLayout.addWidget(self.button_list_unique)
        self.button_compare = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_compare.sizePolicy().hasHeightForWidth())
        self.button_compare.setSizePolicy(sizePolicy)
        self.button_compare.setObjectName("button_compare")
        self.verticalLayout.addWidget(self.button_compare)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.list_a_all = QtGui.QListWidget(self.centralwidget)
        self.list_a_all.setObjectName("list_a_all")
        self.horizontalLayout_3.addWidget(self.list_a_all)
        self.list_b_all = QtGui.QListWidget(self.centralwidget)
        self.list_b_all.setObjectName("list_b_all")
        self.horizontalLayout_3.addWidget(self.list_b_all)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layout_lists = QtGui.QHBoxLayout()
        self.layout_lists.setObjectName("layout_lists")
        self.list_a = QtGui.QListWidget(self.centralwidget)
        self.list_a.setAutoScrollMargin(16)
        self.list_a.setObjectName("list_a")
        self.layout_lists.addWidget(self.list_a)
        self.list_b = QtGui.QListWidget(self.centralwidget)
        self.list_b.setObjectName("list_b")
        self.layout_lists.addWidget(self.list_b)
        self.verticalLayout.addLayout(self.layout_lists)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_unique_a = QtGui.QLabel(self.centralwidget)
        self.label_unique_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_unique_a.setObjectName("label_unique_a")
        self.horizontalLayout.addWidget(self.label_unique_a)
        self.label_unique_b = QtGui.QLabel(self.centralwidget)
        self.label_unique_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_unique_b.setObjectName("label_unique_b")
        self.horizontalLayout.addWidget(self.label_unique_b)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layout_movie_count = QtGui.QHBoxLayout()
        self.layout_movie_count.setObjectName("layout_movie_count")
        self.label_count_a = QtGui.QLabel(self.centralwidget)
        self.label_count_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count_a.setObjectName("label_count_a")
        self.layout_movie_count.addWidget(self.label_count_a)
        self.label_count_b = QtGui.QLabel(self.centralwidget)
        self.label_count_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_count_b.setObjectName("label_count_b")
        self.layout_movie_count.addWidget(self.label_count_b)
        self.verticalLayout.addLayout(self.layout_movie_count)
        self.layout_repair_names = QtGui.QHBoxLayout()
        self.layout_repair_names.setObjectName("layout_repair_names")
        self.button_rename_a = QtGui.QPushButton(self.centralwidget)
        self.button_rename_a.setObjectName("button_rename_a")
        self.layout_repair_names.addWidget(self.button_rename_a)
        self.button_rename_b = QtGui.QPushButton(self.centralwidget)
        self.button_rename_b.setObjectName("button_rename_b")
        self.layout_repair_names.addWidget(self.button_rename_b)
        self.verticalLayout.addLayout(self.layout_repair_names)
        self.layout_copy = QtGui.QHBoxLayout()
        self.layout_copy.setObjectName("layout_copy")
        self.button_copy_ab = QtGui.QPushButton(self.centralwidget)
        self.button_copy_ab.setObjectName("button_copy_ab")
        self.layout_copy.addWidget(self.button_copy_ab)
        self.button_copy_ba = QtGui.QPushButton(self.centralwidget)
        self.button_copy_ba.setObjectName("button_copy_ba")
        self.layout_copy.addWidget(self.button_copy_ba)
        self.verticalLayout.addLayout(self.layout_copy)
        self.layout_ = QtGui.QHBoxLayout()
        self.layout_.setObjectName("layout_")
        self.button_copy_both = QtGui.QPushButton(self.centralwidget)
        self.button_copy_both.setObjectName("button_copy_both")
        self.layout_.addWidget(self.button_copy_both)
        self.verticalLayout.addLayout(self.layout_)
        self.button_cancel = QtGui.QPushButton(self.centralwidget)
        self.button_cancel.setObjectName("button_cancel")
        self.verticalLayout.addWidget(self.button_cancel)
        self.progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.list_log = QtGui.QListWidget(self.centralwidget)
        self.list_log.setMaximumSize(QtCore.QSize(16777215, 150))
        self.list_log.setObjectName("list_log")
        self.verticalLayout.addWidget(self.list_log)
        Movie_app.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Movie_app)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1383, 31))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Movie_app.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Movie_app)
        self.statusbar.setObjectName("statusbar")
        Movie_app.setStatusBar(self.statusbar)
        self.actionI_need_somebody = QtGui.QAction(Movie_app)
        self.actionI_need_somebody.setObjectName("actionI_need_somebody")
        self.menuHelp.addAction(self.actionI_need_somebody)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Movie_app)
        QtCore.QMetaObject.connectSlotsByName(Movie_app)

    def retranslateUi(self, Movie_app):
        Movie_app.setWindowTitle(QtGui.QApplication.translate("Movie_app", "Movie sync", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Movie_app", "Drive A :", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_a.setText(QtGui.QApplication.translate("Movie_app", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Movie_app", "Drive B : ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_b.setText(QtGui.QApplication.translate("Movie_app", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Movie_app", "A Inbox :", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_a_inbox.setText(QtGui.QApplication.translate("Movie_app", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Movie_app", "B Inbox : ", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_b_inbox.setText(QtGui.QApplication.translate("Movie_app", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_volume_a.setText(QtGui.QApplication.translate("Movie_app", "VOLUME NAME:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_volume_b.setText(QtGui.QApplication.translate("Movie_app", "VOLUME NAME:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_list_all.setText(QtGui.QApplication.translate("Movie_app", "List All Movies", None, QtGui.QApplication.UnicodeUTF8))
        self.button_list_unique.setText(QtGui.QApplication.translate("Movie_app", "List Unique Movies", None, QtGui.QApplication.UnicodeUTF8))
        self.button_compare.setText(QtGui.QApplication.translate("Movie_app", "----------   READ DRIVE CONTENTS   ----------", None, QtGui.QApplication.UnicodeUTF8))
        self.label_unique_a.setText(QtGui.QApplication.translate("Movie_app", "Unique movie count on Drive A:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_unique_b.setText(QtGui.QApplication.translate("Movie_app", "Unique movie count on Drive B:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_count_a.setText(QtGui.QApplication.translate("Movie_app", "Total movie count of Drive A:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_count_b.setText(QtGui.QApplication.translate("Movie_app", "Total movie count of Drive B:", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rename_a.setText(QtGui.QApplication.translate("Movie_app", "Repair file names on Drive A", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rename_b.setText(QtGui.QApplication.translate("Movie_app", "Repair file names on Drive B", None, QtGui.QApplication.UnicodeUTF8))
        self.button_copy_ab.setText(QtGui.QApplication.translate("Movie_app", "Copy files to drive B ->", None, QtGui.QApplication.UnicodeUTF8))
        self.button_copy_ba.setText(QtGui.QApplication.translate("Movie_app", "<- Copy files to drive A", None, QtGui.QApplication.UnicodeUTF8))
        self.button_copy_both.setText(QtGui.QApplication.translate("Movie_app", "----------   SYNC   ----------", None, QtGui.QApplication.UnicodeUTF8))
        self.button_cancel.setText(QtGui.QApplication.translate("Movie_app", "CANCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("Movie_app", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionI_need_somebody.setText(QtGui.QApplication.translate("Movie_app", "I need somebody", None, QtGui.QApplication.UnicodeUTF8))

